# Generated by Django 3.0.2 on 2020-01-28 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Psychologist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('country', models.CharField(max_length=50, verbose_name='select country')),
                ('city', models.CharField(max_length=50, verbose_name='psychologist city')),
                ('zip', models.CharField(blank=True, max_length=10, verbose_name='psychologist_zip')),
                ('working_hours', models.CharField(max_length=50, verbose_name='working_hours')),
                ('price_per_hour', models.IntegerField(verbose_name='psychologist prise per hour')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='date_modified')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='restaurant_image')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychologists', to=settings.AUTH_USER_MODEL, verbose_name='Psychologist profile')),
            ],
        ),
    ]
