# Generated by Django 3.0.2 on 2020-01-28 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('psychologists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psychologist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='psychologists', to=settings.AUTH_USER_MODEL),
        ),
    ]
