# Generated by Django 3.0.2 on 2020-02-03 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0002_psychologist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologist',
            name='city',
            field=models.CharField(max_length=50, null=True, verbose_name='psychologist city'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='psychologist_image'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='price_per_hour',
            field=models.IntegerField(blank=True, null=True, verbose_name='psychologist prise per hour'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='working_hours'),
        ),
        migrations.AlterField(
            model_name='psychologist',
            name='zip',
            field=models.IntegerField(blank=True, max_length=10, null=True, verbose_name='psychologist_zip'),
        ),
    ]
