# Generated by Django 3.0.2 on 2020-01-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_auto_20200128_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psychologist',
            name='user_patient',
        ),
    ]
