name: deepTrust_django_app
dependencies:
  - python=3.8
  - psycopg2
  - pip:
      - Django==3.0.2
      - djangorestframework==3.11.0
      - markdown==3.1.1
      - django-filter==2.2.0
      - djangorestframework-simplejwt==4.4.0
      - Pillow==7.0.0
      - flake8==3.7.9
      - django-countries==5.5
      - django-cors-headers==3.2.1
      - django-extensions==2.2.6
      - django-fullurl==1.0