# Generated by Django 3.0.2 on 2020-01-30 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0002_psychologist_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('time', models.SmallIntegerField(choices=[(1, '8:00 - 9:30'), (2, '9:30 - 11:00'), (3, '11:00 - 12:30'), (4, '13:30 - 15:00'), (5, '15:00 - 16:30'), (6, '16:30 - 18:00'), (7, '18:00 - 19:30')])),
                ('visited', models.BooleanField(default=False, verbose_name='visited')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_doctor', to='psychologists.Psychologist', verbose_name='Psychologist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to=settings.AUTH_USER_MODEL, verbose_name='Patient')),
            ],
        ),
    ]
