# Generated by Django 3.0.2 on 2020-02-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_booking_booking_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
