# Generated by Django 3.0.2 on 2020-02-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychologists', '0004_auto_20200203_0907'),
        ('users', '0003_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite_by',
            field=models.ManyToManyField(blank=True, related_name='favourite_by', to='psychologists.Psychologist', verbose_name='favourite'),
        ),
    ]
