# Generated by Django 3.0.2 on 2020-01-28 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('psychologists', '0002_psychologist_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='last name')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='first name')),
                ('problem_description', models.TextField(blank=True, null=True, verbose_name='problem description')),
                ('special_notes', models.TextField(blank=True, null=True, verbose_name='special notes')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('todos', models.TextField(blank=True, null=True, verbose_name='todos')),
                ('psychologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='psychologists.Psychologist')),
            ],
        ),
    ]
