import React from 'react'

const CalendarHardCoded2 = () => {
    return (
        <>
        <div class="calendar-container"><button aria-label="previous week's schedule" class="previous-btn" disabled="">&lt;</button><ul class="dates-container" role="tablist"><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Sunday Feb 09" disabled=""><span>Sun</span>1/09</button></li><li role="presentation" class="active"><button role="tab" aria-selected="true" class="tab-btn" aria-label="Monday Feb 10"><span>Today</span>1/10</button><button class="screen_reader_only" aria-label="go to the schedule">schedule</button></li><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Tuesday Feb 11"><span>Tue</span>1/11</button></li><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Wednesday Feb 12"><span>Wed</span>1/12</button></li><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Thursday Feb 13"><span>Thu</span>1/13</button></li><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Friday Feb 14"><span>Fri</span>1/14</button></li><li role="presentation"><button role="tab" aria-selected="false" class="tab-btn" aria-label="Saturday Feb 15"><span>Sat</span>1/15</button></li></ul><button aria-label="next week's schedule" class="next-btn">&gt;</button></div>
        <div class="schedule-container"><ul class="fitness-classes"><li class="class-details"><div class="class-content"><span class="class-time">8:00 - 9:30</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="sign-up" aria-label="Book  with  at 8:00  - 9:30">AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">9:30 - 11:00</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 9:30  - 11:00 is full">NOT AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">11:00 - 12:30</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 11:00  - 12:30 is full">NOT AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">13:30 - 15:00</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 13:30  - 15:00 is full">NOT AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">15:00 - 16:30</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 15:00  - 16:30 is full">NOT AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">16:30 - 18:00</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 16:30  - 18:00 is full">NOT AVAILABLE</button></li><li class="class-details"><div class="class-content"><span class="class-time">18:00 - 19:30</span><div class="class-specs"><span class="class-name"></span><span class="instructor-name"></span></div></div><button class="class-full" aria-label=" with  at 18:00  - 19:30 is full">NOT AVAILABLE</button></li></ul></div>
        </>
    )
}

export default CalendarHardCoded2